version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "${APP_DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_USER: ${APP_DB_USER}

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "${DOCKER_ADMINER_PORT}:8080"
